#!/usr/bin/env bash
# End-to-end smoke for the F2 python_peer bridge.
#
# Proves byte-for-byte wire compatibility by running a full round-trip
# entirely through the C++ router with Python on both ends:
#
#    publish.py (peer 7) --> router_server --> subscribe.py (peer 3)
#
#   1. Writes a minimal 2-peer UDS profile (peer 3 recorder, peer 7
#      python_tooling) under build/python_peer_smoke/ with a route
#      `source = 7 dest = [3]`.
#   2. Starts router_server with ROUTER_TEST=1 so it self-terminates
#      after idle (no kill signals needed — important because some
#      sandboxes don't permit cross-process kill).
#   3. Starts subscribe.py bound at the peer-3 path (acts as recorder)
#      with --count 5 so it exits after receiving 5 frames.
#   4. Runs publish.py to send 5 frames from peer 7.
#   5. Verifies the router log shows 5 "router: python_tooling ->
#      recorder" lines AND subscribe.py decoded all 5 frames with the
#      expected payloads.
#
# Requirements:
#   - ./build/ipc/test/router_server built (`make all` from repo root)
#   - python3 (no third-party deps)
#
# Tunables:
#   COUNT          number of frames to publish      (default 5)
#   INTERVAL_MS    inter-publish sleep (ms)         (default 30)
#   ROUTER_BIN     router_server binary             (default build/ipc/test/router_server)
#   LOG_DIR        smoke log directory              (default build/python_peer_smoke)

set -u

REPO_ROOT=$(cd "$(dirname "$0")/../../.." && pwd)
ROUTER_BIN=${ROUTER_BIN:-"$REPO_ROOT/build/ipc/test/router_server"}
COUNT=${COUNT:-5}
INTERVAL_MS=${INTERVAL_MS:-30}
LOG_DIR=${LOG_DIR:-"$REPO_ROOT/build/python_peer_smoke"}

PEER_PATH=/tmp/rim_smoke_python_tooling.sock
REC_PATH=/tmp/rim_smoke_recorder.sock
ROUTER_PATH=/tmp/rim_smoke_router.sock

rm -rf "$LOG_DIR"
mkdir -p "$LOG_DIR"
PROFILE="$LOG_DIR/profile.toml"
ROUTER_LOG="$LOG_DIR/router.log"
SUB_LOG="$LOG_DIR/subscribe.log"
PUB_LOG="$LOG_DIR/publish.log"

if [[ ! -x "$ROUTER_BIN" ]]; then
    echo "error: $ROUTER_BIN not built. Run 'make all' first." >&2
    exit 1
fi

rm -f "$ROUTER_PATH" "$REC_PATH" "$PEER_PATH"

cat > "$PROFILE" << EOF
# Phase F F2 smoke profile (auto-generated by smoke.sh).
[router]
listen = "uds:$ROUTER_PATH"

[[peers]]
id    = 3
name  = "recorder"
local = "uds:$REC_PATH"

[[peers]]
id    = 7
name  = "python_tooling"
local = "uds:$PEER_PATH"

[[routes]]
source = 7
dest   = [3]
EOF

echo "[smoke] starting router: $ROUTER_BIN --config $PROFILE"
ROUTER_TEST=1 "$ROUTER_BIN" --config "$PROFILE" >"$ROUTER_LOG" 2>&1 &
ROUTER_PID=$!

for _ in $(seq 1 30); do
    if [[ -S "$ROUTER_PATH" ]]; then break; fi
    sleep 0.1
done
if [[ ! -S "$ROUTER_PATH" ]]; then
    echo "[smoke] router did not create $ROUTER_PATH; last log:" >&2
    tail -n 40 "$ROUTER_LOG" >&2 || true
    rm -f "$ROUTER_PATH" "$REC_PATH" "$PEER_PATH"
    exit 1
fi

echo "[smoke] starting Python subscriber as peer 3 (count=$COUNT)"
python3 "$REPO_ROOT/examples/bridges/python_peer/subscribe.py" \
    --router-path "$ROUTER_PATH" \
    --peer-path "$REC_PATH" \
    --peer-id 3 \
    --count "$COUNT" \
    >"$SUB_LOG" 2>&1 &
SUB_PID=$!

sleep 0.2

echo "[smoke] publishing $COUNT frames as peer 7"
python3 "$REPO_ROOT/examples/bridges/python_peer/publish.py" \
    --router-path "$ROUTER_PATH" \
    --peer-path "$PEER_PATH" \
    --peer-id 7 \
    --count "$COUNT" \
    --interval-ms "$INTERVAL_MS" \
    >"$PUB_LOG" 2>&1
PUB_RC=$?

wait "$SUB_PID"
SUB_RC=$?
wait "$ROUTER_PID"
ROUTER_RC=$?

rm -f "$ROUTER_PATH" "$REC_PATH" "$PEER_PATH"

echo
echo "===== router.log ====="
cat "$ROUTER_LOG"
echo
echo "===== publish.log ====="
cat "$PUB_LOG"
echo
echo "===== subscribe.log ====="
cat "$SUB_LOG"
echo

if [[ "$PUB_RC" -ne 0 ]]; then
    echo "[smoke] FAIL: publish.py exited with $PUB_RC" >&2
    exit "$PUB_RC"
fi
if [[ "$SUB_RC" -ne 0 ]]; then
    echo "[smoke] FAIL: subscribe.py exited with $SUB_RC" >&2
    exit "$SUB_RC"
fi
if [[ "$ROUTER_RC" -ne 0 ]]; then
    echo "[smoke] FAIL: router_server exited with $ROUTER_RC" >&2
    exit "$ROUTER_RC"
fi

FORWARDED=$(grep -c "router: python_tooling -> recorder" "$ROUTER_LOG" || true)
RECEIVED=$(grep -c "^\[recv\] source=python_tooling" "$SUB_LOG" || true)
echo "[smoke] router forwarded $FORWARDED frame(s); subscriber decoded $RECEIVED frame(s) (expected $COUNT)"

if [[ "$FORWARDED" -lt "$COUNT" ]]; then
    echo "[smoke] FAIL: forwarded count below expected" >&2
    exit 1
fi
if [[ "$RECEIVED" -lt "$COUNT" ]]; then
    echo "[smoke] FAIL: subscriber received fewer than expected" >&2
    exit 1
fi

for seq in $(seq 0 $((COUNT - 1))); do
    if ! grep -E "seq=$seq .* payload=b'python-tooling-$seq'" "$SUB_LOG" > /dev/null; then
        echo "[smoke] FAIL: subscriber did not see seq=$seq with expected payload" >&2
        exit 1
    fi
done

echo "[smoke] OK — Python <-> C++ wire format parity verified"
