#!/usr/bin/env bash
# End-to-end smoke for the F3 node_gateway bridge.
#
# Proves byte-for-byte wire compatibility plus WebSocket fan-out by
# running a full chain entirely through the C++ router with Node on both
# ends and a stdlib WebSocket transport in the middle:
#
#    publish.js (peer 1, UDP)
#      |
#      v
#    router_server (UDP profile)
#      |
#      v
#    gateway.js (peer 8, UDP) --[WebSocket text frame]--> ws_test_client.js
#
#   1. Writes a minimal 2-peer UDP profile (peer 1 sensor, peer 8
#      dashboard_feed) under build/node_gateway_smoke/ with a route
#      `source = 1 dest = [8]`.
#   2. Starts router_server with ROUTER_TEST=1 so it self-terminates
#      after idle (no kill signals needed — important in sandboxed CI).
#   3. Starts gateway.js as peer 8, binding the dashboard UDP port and
#      a WebSocket server on $WS_PORT; waits for the "[gateway] ws
#      listening" line to confirm readiness.
#   4. Starts ws_test_client.js connecting to ws://127.0.0.1:$WS_PORT
#      with --count $COUNT so it exits after receiving $COUNT broadcasts.
#   5. Runs publish.js to send $COUNT frames from peer 1.
#   6. Verifies the router log shows $COUNT "router: sensor ->
#      dashboard_feed" lines AND ws_test_client decoded all $COUNT
#      broadcasts with the expected payloads (one JSON line per frame,
#      payload_text == "node-frame-<seq>").
#
# Requirements:
#   - ./build/ipc/test/router_server built (`make all` from repo root)
#   - node (>=18) on PATH; no npm install required (stdlib only)
#
# Tunables:
#   COUNT          number of frames to publish      (default 5)
#   INTERVAL_MS    inter-publish sleep (ms)         (default 30)
#   WS_PORT        WebSocket TCP port               (default 25080)
#   ROUTER_BIN     router_server binary             (default build/ipc/test/router_server)
#   LOG_DIR        smoke log directory              (default build/node_gateway_smoke)
#   ROUTER_UDP_PORT  router listen port             (default 25100)
#   SENSOR_UDP_PORT  sensor (peer 1) port           (default 25101)
#   DASH_UDP_PORT    dashboard (peer 8) port        (default 25108)

set -u

REPO_ROOT=$(cd "$(dirname "$0")/../../.." && pwd)
ROUTER_BIN=${ROUTER_BIN:-"$REPO_ROOT/build/ipc/test/router_server"}
COUNT=${COUNT:-5}
INTERVAL_MS=${INTERVAL_MS:-30}
WS_PORT=${WS_PORT:-25080}
LOG_DIR=${LOG_DIR:-"$REPO_ROOT/build/node_gateway_smoke"}

ROUTER_UDP_PORT=${ROUTER_UDP_PORT:-25100}
SENSOR_UDP_PORT=${SENSOR_UDP_PORT:-25101}
DASH_UDP_PORT=${DASH_UDP_PORT:-25108}

rm -rf "$LOG_DIR"
mkdir -p "$LOG_DIR"
PROFILE="$LOG_DIR/profile.toml"
ROUTER_LOG="$LOG_DIR/router.log"
GW_LOG="$LOG_DIR/gateway.log"
WS_LOG="$LOG_DIR/ws_client.log"
PUB_LOG="$LOG_DIR/publish.log"

if [[ ! -x "$ROUTER_BIN" ]]; then
    echo "error: $ROUTER_BIN not built. Run 'make all' first." >&2
    exit 1
fi

if ! command -v node >/dev/null 2>&1; then
    echo "[smoke] skip: node not found on PATH" >&2
    exit 0
fi

# Some sandboxes (CI, Cursor agent default) block AF_INET socket()
# entirely. The router fails with "failed to create socket" in that case.
# Probe with a tiny Node snippet so we skip cleanly instead of FAILing.
if ! node -e "const d=require('dgram');const s=d.createSocket('udp4');s.on('error',e=>{process.exit(7)});s.bind({address:'127.0.0.1',port:0,exclusive:true},()=>{s.close(()=>process.exit(0))});setTimeout(()=>{s.close();process.exit(8)},500);" >/dev/null 2>&1; then
    echo "[smoke] skip: AF_INET / UDP loopback unavailable in this environment" >&2
    exit 0
fi

cat > "$PROFILE" << EOF
# Phase F F3 smoke profile (auto-generated by smoke.sh).
[router]
listen = "udp:127.0.0.1:$ROUTER_UDP_PORT"

[[peers]]
id    = 1
name  = "sensor"
local = "udp:127.0.0.1:$SENSOR_UDP_PORT"

[[peers]]
id    = 8
name  = "dashboard_feed"
local = "udp:127.0.0.1:$DASH_UDP_PORT"

[[routes]]
source = 1
dest   = [8]
EOF

echo "[smoke] starting router: $ROUTER_BIN --config $PROFILE"
ROUTER_TEST=1 "$ROUTER_BIN" --config "$PROFILE" >"$ROUTER_LOG" 2>&1 &
ROUTER_PID=$!

# Router opens UDP immediately on bind. Give it a brief grace window.
sleep 0.2
if ! kill -0 "$ROUTER_PID" 2>/dev/null; then
    echo "[smoke] router exited before publish; last log:" >&2
    tail -n 40 "$ROUTER_LOG" >&2 || true
    exit 1
fi

echo "[smoke] starting Node gateway as peer 8 (count=$COUNT, ws_port=$WS_PORT)"
node "$REPO_ROOT/examples/bridges/node_gateway/gateway.js" \
    --router-host 127.0.0.1 --router-port "$ROUTER_UDP_PORT" \
    --peer-host   127.0.0.1 --peer-port   "$DASH_UDP_PORT" \
    --peer-id     8 \
    --ws-host     127.0.0.1 --ws-port     "$WS_PORT" \
    --count       "$COUNT" \
    >"$GW_LOG" 2>&1 &
GW_PID=$!

# Wait for "[gateway] ws listening" — gateway's stable readiness contract.
for _ in $(seq 1 30); do
    if grep -q "^\[gateway\] ws listening " "$GW_LOG" 2>/dev/null; then break; fi
    if ! kill -0 "$GW_PID" 2>/dev/null; then
        echo "[smoke] gateway exited before WS listening; last log:" >&2
        tail -n 60 "$GW_LOG" >&2 || true
        kill -TERM "$ROUTER_PID" 2>/dev/null || true
        wait "$ROUTER_PID" 2>/dev/null || true
        exit 1
    fi
    sleep 0.1
done
if ! grep -q "^\[gateway\] ws listening " "$GW_LOG" 2>/dev/null; then
    echo "[smoke] gateway did not log 'ws listening' within 3s; last log:" >&2
    tail -n 60 "$GW_LOG" >&2 || true
    kill -TERM "$GW_PID" 2>/dev/null || true
    kill -TERM "$ROUTER_PID" 2>/dev/null || true
    wait "$GW_PID" 2>/dev/null || true
    wait "$ROUTER_PID" 2>/dev/null || true
    exit 1
fi

echo "[smoke] starting WebSocket test client (count=$COUNT)"
node "$REPO_ROOT/examples/bridges/node_gateway/ws_test_client.js" \
    --host 127.0.0.1 --port "$WS_PORT" \
    --count "$COUNT" \
    --connect-timeout-ms 3000 \
    >"$WS_LOG" 2>&1 &
WS_PID=$!

# Brief grace for the client to complete its upgrade before publish starts.
sleep 0.2

echo "[smoke] publishing $COUNT frames as peer 1 (sensor)"
node "$REPO_ROOT/examples/bridges/node_gateway/publish.js" \
    --router-host 127.0.0.1 --router-port "$ROUTER_UDP_PORT" \
    --peer-host   127.0.0.1 --peer-port   "$SENSOR_UDP_PORT" \
    --peer-id     1 \
    --count       "$COUNT" \
    --interval-ms "$INTERVAL_MS" \
    --payload     "node-frame" \
    >"$PUB_LOG" 2>&1
PUB_RC=$?

wait "$WS_PID"
WS_RC=$?
wait "$GW_PID"
GW_RC=$?
wait "$ROUTER_PID"
ROUTER_RC=$?

echo
echo "===== router.log ====="
cat "$ROUTER_LOG"
echo
echo "===== publish.log ====="
cat "$PUB_LOG"
echo
echo "===== gateway.log ====="
cat "$GW_LOG"
echo
echo "===== ws_client.log ====="
cat "$WS_LOG"
echo

if [[ "$PUB_RC" -ne 0 ]]; then
    echo "[smoke] FAIL: publish.js exited with $PUB_RC" >&2
    exit "$PUB_RC"
fi
if [[ "$WS_RC" -ne 0 ]]; then
    echo "[smoke] FAIL: ws_test_client.js exited with $WS_RC" >&2
    exit "$WS_RC"
fi
if [[ "$GW_RC" -ne 0 ]]; then
    echo "[smoke] FAIL: gateway.js exited with $GW_RC" >&2
    exit "$GW_RC"
fi
if [[ "$ROUTER_RC" -ne 0 ]]; then
    echo "[smoke] FAIL: router_server exited with $ROUTER_RC" >&2
    exit "$ROUTER_RC"
fi

FORWARDED=$(grep -c "router: sensor -> dashboard_feed" "$ROUTER_LOG" || true)
BROADCAST=$(grep -c "^\[broadcast\] " "$WS_LOG" || true)
echo "[smoke] router forwarded $FORWARDED frame(s); ws client received $BROADCAST broadcast(s) (expected $COUNT)"

if [[ "$FORWARDED" -lt "$COUNT" ]]; then
    echo "[smoke] FAIL: forwarded count below expected" >&2
    exit 1
fi
if [[ "$BROADCAST" -lt "$COUNT" ]]; then
    echo "[smoke] FAIL: WebSocket client received fewer broadcasts than expected" >&2
    exit 1
fi

# Verify every seq carried its expected payload byte-for-byte. Each
# broadcast line is a JSON object whose payload_text field contains the
# string "node-frame-<seq>". A literal substring check avoids dragging
# in a JSON parser.
for seq in $(seq 0 $((COUNT - 1))); do
    pat="\"seq\":$seq,.*\"payload_text\":\"node-frame-$seq\""
    if ! grep -E "$pat" "$WS_LOG" > /dev/null; then
        echo "[smoke] FAIL: WebSocket client did not see seq=$seq with expected payload" >&2
        exit 1
    fi
done

echo "[smoke] OK — Node <-> C++ router <-> WebSocket parity verified"
